### PR TITLE
gha: fix code coverage reports

### LINKED ISSUE #5: ci: fix coverage reports
The coverage job is combining and running the full coverage session, resulting in [ci failing](https://github.com/opendatahub-io/caikit-nlp-client/actions/runs/6786184913/job/18446221262)

It should only be combining and uploading the combined results.

### PR DESCRIPTION
**Pull request by dtrifiro**
- gha: fix code coverage reports
- gha: only run on main branch and/or pull requests
- gha: add concurrency config

### CODE REVIEW

**Comment by dtrifiro** [comment]
Note: we still have to add the codecov token to the repo in order to code coverage reports to be actually uploaded to codecov

**Comment by dtrifiro** [comment]
Closes https://github.com/opendatahub-io/caikit-nlp-client/issues/5

**Review by z103cb — COMMENTED** [review]
These look OK, but there's a failure: https://github.com/opendatahub-io/caikit-nlp-client/actions/runs/6788674606/job/18454181756

I think I would like that fixed before merging.

**Comment by dtrifiro** [comment]
@z103cb thanks, fixed in the last push!

**Review by z103cb — APPROVED** [review]
LGTM.

**Pull request merged**
